postgres:
  image: postgres:11.1-alpine
  ports:
    - '5432:5432'
  container_name: postgres_films
  environment:
    POSTGRES_USER: 'hameiste'
    POSTGRES_PASSWORD: 'hameistePW'
  volumes:
    - ./init:/docker-entrypoint-initdb.d/